name: dev-build
description: dev-build action for the pipeline

inputs:
  SERVICE_ACCOUNT_KEYFILE_JSON:
    description: dev env's service account keyfile json
    required: true

  ARTIFACTORY_USER:
    description: App's Artifactory user name
    required: true
  
  ARTIFACTORY_PASS:
    description: App's Artifactory passcode
    required: true

  CLIENT_ID:
    description: dev env's Cliend ID
    required: true

  CLIENT_SECRET:
    description: dev env's Client Secret
    required: true


runs:
  using: "composite"
  
  - name: Github actions authentication...
    uses: google-github-actions/auth@v1
    with:
      credentials_json: ${{inputs.SERVICE_ACCOUNT_KEYFILE_JSON}}

  - name: Building project...
    shell: bash
    run: |
      credentials_json: ${{inputs.SERVICE_ACCOUNT_KEYFILE_JSON}}
      sed -i 's/${env.ARTIFACTORY_USER}/${{inputs.ARTIFACTORY_USER}}/' .m2/settings.xml
      sed -i 's/${env.ARTIFACTORY_PASS}/${{inputs.env.ARTIFACTORY_PASS}}/' .m2/settings.xml
      npm install -g @angular/cli
      mvn -s .m2/settings.xml --batch-mode clean install -Dclient-id=${{inputs.CLIENT_ID}} -Dclient-secret=${{inputs.CLIENT_SECRET}} -P dev
