name: dev Runner

on: workflow_dispatch

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest
    container: node:16-alpine
    
    steps:
    - name: Repo Checkout...
      uses: actions/checkout@v3
    
    - name: Setting up environment for build...
      run: |
        apk add --no-cache git maven bash curl wget
        apk --no-cache add openjdk17-jdk
        apk add --no-cache python3 py3-pip
        curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-425.0.0-linux-x86_64.tar.gz > /tmp/google-cloud-cli.tar.gz
        mkdir -p /usr/local/gcloud
        tar -xzf /tmp/google-cloud-cli.tar.gz -C /usr/local/gcloud
        chmod -R 777 /usr/local/gcloud/
        /usr/local/gcloud/google-cloud-sdk/install.sh --quiet
        echo $PATH
        PATH=$PATH:/usr/local/gcloud/google-cloud-sdk/bin

    - name: Building...
      uses: ./.github/actions/dev-build
      with:
        SERVICE_ACCOUNT_KEYFILE_JSON: ${{ secrets.SERVICE_ACCOUNT_KEYFILE_JSON }}
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    
    - name: Deploying...
      uses: ./.github/actions/dev-deploy
